import type { DashboardBrief } from "@/lib/brief/pipeline";
import { weatherImpact } from "@/lib/brief/signals";
import { RegenerateButton } from "./RegenerateButton";

/** The full dashboard render: headline stats, narrative, and the signal cards. */
export function BriefView({ data, date }: { data: DashboardBrief; date: string }) {
  const { context: ctx, brief } = data;
  const h = ctx.headline;
  const impact = weatherImpact(ctx.weather.precipChance, ctx.weather.condition);

  return (
    <div className="wrap">
      <div className="topbar">
        <div>
          <div className="eyebrow">Pre-Shift Brief</div>
          <h1>{ctx.restaurantName}</h1>
          <div className="sub">
            {ctx.serviceLabel} · {formatDate(ctx.date)}
            {data.model ? ` · generated by ${data.model}` : ""}
          </div>
        </div>
        <RegenerateButton date={date} />
      </div>

      <div className="stat-row">
        <Stat num={h.totalCovers} lbl="Covers" />
        <Stat num={h.totalReservations} lbl="Reservations" />
        <Stat num={h.peakWindow ?? "—"} lbl="Peak window" small />
        <Stat num={h.firstTimerCount} lbl="First-timers" />
        <Stat num={h.regularCount} lbl="Regulars" />
        <Stat num={h.vipCount} lbl="VIPs" />
      </div>

      {data.narrativeError && (
        <div className="notice">
          Showing tonight&apos;s data. The AI narrative isn&apos;t available right now
          {data.narrativeError.includes("ANTHROPIC_API_KEY")
            ? " — set ANTHROPIC_API_KEY to enable it."
            : `: ${data.narrativeError}`}
        </div>
      )}

      <div className="grid">
        <div>
          {brief && (
            <div className="card">
              <h2>The brief — read this aloud (~90s)</h2>
              <div className="narrative">{brief.narrative}</div>
            </div>
          )}

          {brief && brief.hitList.length > 0 && (
            <div className="card">
              <h2>Hit list</h2>
              <ul className="list">
                {brief.hitList.map((item, i) => (
                  <li key={i}>{item}</li>
                ))}
              </ul>
            </div>
          )}

          <div className="card">
            <h2>White-glove tonight</h2>
            {ctx.whiteGlove.length === 0 ? (
              <div className="muted">No flagged regulars tonight.</div>
            ) : (
              <ul className="list">
                {ctx.whiteGlove.map((w, i) => (
                  <li key={i}>
                    <span className="pill glove">VIP care</span>
                    <span>
                      <strong>{w.guestName}</strong> — {w.reason}
                      {w.notes ? <span className="muted"> · {w.notes}</span> : null}
                    </span>
                  </li>
                ))}
              </ul>
            )}
          </div>

          <div className="card">
            <h2>First-timers — win them tonight</h2>
            {ctx.firstTimers.length === 0 ? (
              <div className="muted">No first-timers on the book.</div>
            ) : (
              <ul className="list">
                {ctx.firstTimers.map((f, i) => (
                  <li key={i}>
                    <span className="pill time">{f.time}</span>
                    <span>
                      {f.guestName ?? "Walk-in"} · party of {f.partySize}{" "}
                      {f.channel === "google" && <span className="pill google">Google</span>}
                    </span>
                  </li>
                ))}
              </ul>
            )}
          </div>
        </div>

        <div>
          <div className="card">
            <h2>Weather</h2>
            <div className="weather">
              <div className="temp">{ctx.weather.tempF ? `${ctx.weather.tempF}°` : "—"}</div>
              <div>
                <div>{ctx.weather.condition}</div>
                <div className="muted">{ctx.weather.precipChance}% precip</div>
              </div>
            </div>
            {impact && <div className="muted" style={{ marginTop: 10 }}>{impact}</div>}
          </div>

          <div className="card">
            <h2>86 board</h2>
            <ul className="list">
              {ctx.eightySix.map((e, i) => (
                <li key={i}>
                  <span className={`pill ${e.available ? "push" : "eightysix"}`}>
                    {e.available ? "PUSH" : "86"}
                  </span>
                  <span>
                    <strong>{e.name}</strong>
                    {e.reason ? <span className="muted"> · {e.reason}</span> : null}
                  </span>
                </li>
              ))}
            </ul>
          </div>

          {ctx.allergies.length > 0 && (
            <div className="card">
              <h2>Allergy tables</h2>
              <ul className="list">
                {ctx.allergies.map((a, i) => (
                  <li key={i}>
                    <span className="pill time">{a.time}</span>
                    <span>
                      <strong>{a.guestName}</strong> · {a.allergies.join(", ")}
                    </span>
                  </li>
                ))}
              </ul>
            </div>
          )}

          {ctx.largeParties.length > 0 && (
            <div className="card">
              <h2>Large parties</h2>
              <ul className="list">
                {ctx.largeParties.map((l, i) => (
                  <li key={i}>
                    <span className="pill time">{l.time}</span>
                    <span>
                      Party of {l.partySize}
                      {l.guestName ? ` · ${l.guestName}` : ""}
                      {l.tags.length ? <span className="muted"> · {l.tags.join(", ")}</span> : null}
                    </span>
                  </li>
                ))}
              </ul>
            </div>
          )}

          <div className="card upsell">
            <h2>Tonight&apos;s upsell push</h2>
            <div className="line">{brief?.upsellLine ?? ctx.upsell.item}</div>
            <div className="muted">{ctx.upsell.why}</div>
            <ul className="list" style={{ marginTop: 8 }}>
              {ctx.upsell.talkingPoints.map((t, i) => (
                <li key={i}>{t}</li>
              ))}
            </ul>
          </div>
        </div>
      </div>

      <div className="footer">
        {data.generatedAt
          ? `Generated ${new Date(data.generatedAt).toLocaleString()}`
          : "Data assembled live"}{" "}
        · Provider: {process.env.DATA_PROVIDER || "seed"} · Runs off data you already have.
      </div>
    </div>
  );
}

function Stat({ num, lbl, small }: { num: string | number; lbl: string; small?: boolean }) {
  return (
    <div className="stat">
      <div className="num" style={small ? { fontSize: 18 } : undefined}>
        {num}
      </div>
      <div className="lbl">{lbl}</div>
    </div>
  );
}

function formatDate(iso: string): string {
  const [y, m, d] = iso.split("-").map(Number);
  return new Date(y, m - 1, d).toLocaleDateString(undefined, {
    weekday: "long",
    month: "long",
    day: "numeric",
  });
}
