/**
 * CLI: print tonight's pre-shift brief to the console.
 *
 *   npm run brief            # full pipeline (needs ANTHROPIC_API_KEY)
 *   npm run brief -- --no-ai # assemble + print derived signals only, no Claude
 *   npm run brief -- --date 2026-06-21
 *
 * `--no-ai` verifies the whole data layer (providers + signals) with zero keys.
 */
import { assembleContext } from "@/lib/brief/assembleContext";
import { buildBrief, todayIso } from "@/lib/brief/pipeline";
import type { BriefContext } from "@/lib/types";

function arg(flag: string): string | undefined {
  const i = process.argv.indexOf(flag);
  return i !== -1 ? process.argv[i + 1] : undefined;
}

const noAi = process.argv.includes("--no-ai");
const date = arg("--date") || todayIso();

function line(s = ""): void {
  process.stdout.write(s + "\n");
}

function printContext(ctx: BriefContext): void {
  line(`\n=== ${ctx.restaurantName} — ${ctx.serviceLabel}, ${ctx.date} ===`);
  const h = ctx.headline;
  line(
    `Covers ${h.totalCovers} / ${h.totalReservations} res · peak ${h.peakWindow ?? "—"} · ` +
      `first-timers ${h.firstTimerCount} · regulars ${h.regularCount} · VIPs ${h.vipCount}`,
  );

  line("\nFirst-timers:");
  ctx.firstTimers.forEach((f) =>
    line(`  ${f.time} · ${f.partySize}-top${f.guestName ? ` · ${f.guestName}` : ""} (${f.channel})`),
  );

  line("\nWhite-glove:");
  ctx.whiteGlove.forEach((w) => line(`  ${w.guestName} — ${w.reason}`));

  line("\n86 / availability:");
  ctx.eightySix.forEach((e) =>
    line(`  ${e.available ? "[push]" : "[86] "} ${e.name}${e.reason ? ` — ${e.reason}` : ""}`),
  );

  line(`\nWeather: ${ctx.weather.tempF}°F, ${ctx.weather.condition}, ${ctx.weather.precipChance}% precip`);
  line(`Upsell: ${ctx.upsell.item} — ${ctx.upsell.why}`);
}

async function main(): Promise<void> {
  if (noAi) {
    const ctx = await assembleContext(date);
    printContext(ctx);
    line("\n(--no-ai: skipped Claude generation)\n");
    return;
  }

  const { context, brief, model } = await buildBrief(date, true);
  printContext(context);

  line(`\n=== BRIEF (generated by ${model}) ===\n`);
  line(brief.narrative);
  line("\nHit list:");
  brief.hitList.forEach((h) => line(`  • ${h}`));
  line("\nWhite-glove:");
  brief.whiteGlove.forEach((w) => line(`  • ${w}`));
  line("\n86:");
  brief.eightySix.forEach((e) => line(`  • ${e}`));
  line(`\nUpsell line: ${brief.upsellLine}\n`);
}

main().catch((err) => {
  console.error("\n[brief] failed:", err.message);
  process.exit(1);
});
